name: Live Paper Monitor
on:
  workflow_dispatch:
  # schedule:
    # - cron: '10 */1 * * *'
    # - cron: '10 */3 * * *'
jobs:
  VerifyData:
    runs-on: ubuntu-latest
    steps:
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install Faker

      - name: execute py script
        run: python ./.github/workflows/checkData.py